// <auto-generated />
using BusApp.Dataa.Concrete.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusApp.Dataa.Migrations
{
    [DbContext(typeof(BusDbContext))]
    [Migration("20220522223525_mig2")]
    partial class mig2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusApp.Entity.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusDriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusPlaque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusSeatNumber")
                        .HasColumnType("int");

                    b.HasKey("BusId");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("BusApp.Entity.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("BusApp.Entity.Expedition", b =>
                {
                    b.Property<int>("ExpeditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<string>("ExpeditionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpeditionFinish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpeditionHour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExpeditionPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExpeditionStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpeditionStation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpeditionId");

                    b.HasIndex("BusId");

                    b.ToTable("Expeditions");
                });

            modelBuilder.Entity("BusApp.Entity.Expedition", b =>
                {
                    b.HasOne("BusApp.Entity.Bus", "Bus")
                        .WithMany("Expeditions")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("BusApp.Entity.Bus", b =>
                {
                    b.Navigation("Expeditions");
                });
#pragma warning restore 612, 618
        }
    }
}
