// <auto-generated />
using System;
using BusApp.Dataa.Concrete.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusApp.Dataa.Migrations
{
    [DbContext(typeof(BusDbContext))]
    partial class BusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("BusApp.Entity.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusDriverName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusPlaque")
                        .HasColumnType("TEXT");

                    b.Property<int>("BusSeatNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("BusId");

                    b.ToTable("Buses");
                });

            modelBuilder.Entity("BusApp.Entity.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityName")
                        .HasColumnType("TEXT");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("BusApp.Entity.Expedition", b =>
                {
                    b.Property<int>("ExpeditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpeditionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpeditionFinish")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpeditionHour")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpeditionPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpeditionStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpeditionStation")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PassengerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExpeditionId");

                    b.HasIndex("BusId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Expeditions");
                });

            modelBuilder.Entity("BusApp.Entity.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("PassengerId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("BusApp.Entity.Expedition", b =>
                {
                    b.HasOne("BusApp.Entity.Bus", "Bus")
                        .WithMany("Expeditions")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusApp.Entity.Passenger", "passenger")
                        .WithMany("expeditions")
                        .HasForeignKey("PassengerId");

                    b.Navigation("Bus");

                    b.Navigation("passenger");
                });

            modelBuilder.Entity("BusApp.Entity.Bus", b =>
                {
                    b.Navigation("Expeditions");
                });

            modelBuilder.Entity("BusApp.Entity.Passenger", b =>
                {
                    b.Navigation("expeditions");
                });
#pragma warning restore 612, 618
        }
    }
}
